## Test Only

In [4]:
import torch
import torch.nn.functional as F

## Load snappy parquet

In [16]:
# Load the snappy parquet data
import pyarrow.parquet as pq
import pandas as pd
import os
import yaml

# Load the data
data_dir = os.path.expanduser('~/Downloads/data/characters.snappy.parquet')
table = pq.read_table(data_dir)
df = table.to_pandas()
# Peep the columns and data according to the column config in config.yaml
yaml_file = './ml_prototype/mm_embedding/config.yaml'
with open(yaml_file, 'r') as f:
    config = yaml.safe_load(f)
    columns = [col["name"] for col in config["my_config"]["data_module"]["columns"]]
    df = df[columns]
    print(df.columns)
    print(df.head())

Index(['age', 'user rating', 'number of conversations', 'creativity', 'energy',
       'speed', 'strength', 'voice id', 'sarcasm level', 'humor level',
       'politeness level', 'emotional range', 'speech style', 'moral level',
       'occupation', 'personality', 'gender'],
      dtype='object')
        age  user rating  number of conversations  creativity  energy   speed  \
0  24918611     1.175968                  9483350         379   71998  411308   
1  31671782     3.760094                  2021807         686   19670  243713   
2  85260317     2.593144                  4433147         922   61021   45108   
3  50338035     4.670698                  7594932         592    8052  334363   
4  90007500     1.399313                   501337         278   71171   55043   

   strength  voice id  sarcasm level  humor level  politeness level  \
0     56889  74625846              0            3                 2   
1     33006  96424650              4            7                 9   
2 

In [10]:
input_data = torch.tensor([
            [1], [2], [3]
        ])
print(input_data.shape)
res = F.one_hot(input_data, num_classes=4)
print(res.shape)

print(res)
print(res[0])
print(res.squeeze(1))

torch.Size([3, 1])
torch.Size([3, 1, 4])
tensor([[[0, 1, 0, 0]],

        [[0, 0, 1, 0]],

        [[0, 0, 0, 1]]])
tensor([[0, 1, 0, 0]])
tensor([[0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])
